#!/usr/bin/env python3
"""
MCP Generator Server - A Model Context Protocol server that generates other MCP servers.
This meta-MCP server helps developers quickly scaffold new MCP servers with best practices.
"""

import asyncio
import json
import os
from pathlib import Path
from typing import Any, Optional

from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import (
    Tool,
    TextContent,
    ImageContent,
    EmbeddedResource,
    LoggingLevel
)

# Initialize the MCP server
app = Server("mcp-generator")

# Template directory
TEMPLATE_DIR = Path(__file__).parent / "templates"


class MCPTemplate:
    """Represents a MCP server template"""

    @staticmethod
    def basic_tool_server(name: str, description: str, tools: list[dict]) -> dict:
        """Generate a basic tool-based MCP server"""

        tool_implementations = []
        tool_definitions = []
        newline = "\n"

        for tool in tools:
            tool_name = tool.get("name", "example_tool")
            tool_desc = tool.get("description", "Example tool")
            tool_params = tool.get("parameters", [])

            # Generate tool implementation
            params_str = ", ".join([f"{p['name']}: {p.get('type', 'str')}" for p in tool_params])
            param_extraction = newline.join([f"        {p['name']} = arguments.get('{p['name']}')" for p in tool_params])
            tool_implementations.append(f'''
@app.call_tool()
async def call_tool(name: str, arguments: Any) -> list[TextContent]:
    """Handle tool execution requests"""
    if name == "{tool_name}":
        # Extract parameters
        {param_extraction}

        # TODO: Implement {tool_name} logic here
        result = f"Executed {tool_name}"

        return [TextContent(type="text", text=result)]

    raise ValueError(f"Unknown tool: {{name}}")
''')

            # Generate tool definition
            input_schema = {
                "type": "object",
                "properties": {
                    p["name"]: {
                        "type": p.get("type", "string"),
                        "description": p.get("description", "")
                    } for p in tool_params
                },
                "required": [p["name"] for p in tool_params if p.get("required", False)]
            }

            tool_definitions.append(f'''
        Tool(
            name="{tool_name}",
            description="{tool_desc}",
            inputSchema={json.dumps(input_schema, indent=16)}
        )''')

        code = f'''#!/usr/bin/env python3
"""
{name} - {description}
Auto-generated by MCP Generator
"""

import asyncio
from typing import Any
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent

# Initialize the MCP server
app = Server("{name}")

@app.list_tools()
async def list_tools() -> list[Tool]:
    """List available tools"""
    return [{"".join(tool_definitions)}
    ]

{"".join(tool_implementations)}

async def main():
    """Run the MCP server"""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )

if __name__ == "__main__":
    asyncio.run(main())
'''
        return {
            "server.py": code,
            "README.md": f"# {name}\n\n{description}\n\n## Installation\n\n```bash\npip install -r requirements.txt\n```\n\n## Usage\n\n```bash\npython server.py\n```",
            "requirements.txt": "mcp>=0.9.0\n"
        }

    @staticmethod
    def resource_server(name: str, description: str, resources: list[dict]) -> dict:
        """Generate a resource-based MCP server"""

        resource_handlers = []
        resource_definitions = []

        for resource in resources:
            res_uri = resource.get("uri", "resource://example")
            res_name = resource.get("name", "Example Resource")
            res_desc = resource.get("description", "Example resource")
            res_type = resource.get("type", "text")

            resource_handlers.append(f'''
    if uri.startswith("{res_uri}"):
        # TODO: Implement {res_name} data fetching
        content = "Sample data for {res_name}"
        return [TextContent(type="text", text=content)]
''')

            resource_definitions.append(f'''
        EmbeddedResource(
            uri="{res_uri}",
            name="{res_name}",
            description="{res_desc}",
            mimeType="text/plain" if "{res_type}" == "text" else "application/json"
        )''')

        code = f'''#!/usr/bin/env python3
"""
{name} - {description}
Auto-generated by MCP Generator
"""

import asyncio
from typing import Any
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Resource, TextContent, EmbeddedResource

# Initialize the MCP server
app = Server("{name}")

@app.list_resources()
async def list_resources() -> list[Resource]:
    """List available resources"""
    return [{"".join(resource_definitions)}
    ]

@app.read_resource()
async def read_resource(uri: str) -> str:
    """Read a specific resource"""
    {"".join(resource_handlers)}

    raise ValueError(f"Unknown resource: {{uri}}")

async def main():
    """Run the MCP server"""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )

if __name__ == "__main__":
    asyncio.run(main())
'''
        return {
            "server.py": code,
            "README.md": f"# {name}\n\n{description}\n\n## Installation\n\n```bash\npip install -r requirements.txt\n```\n\n## Usage\n\n```bash\npython server.py\n```",
            "requirements.txt": "mcp>=0.9.0\n"
        }

    @staticmethod
    def full_server(name: str, description: str, config: dict) -> dict:
        """Generate a full-featured MCP server with tools, resources, and prompts"""

        tools = config.get("tools", [])
        resources = config.get("resources", [])
        prompts = config.get("prompts", [])
        newline = "\n"

        # Generate tools section
        tool_list = []
        tool_handlers = []

        for tool in tools:
            tool_name = tool.get("name", "example_tool")
            tool_desc = tool.get("description", "Example tool")
            tool_params = tool.get("parameters", [])

            input_schema = {
                "type": "object",
                "properties": {
                    p["name"]: {
                        "type": p.get("type", "string"),
                        "description": p.get("description", "")
                    } for p in tool_params
                },
                "required": [p["name"] for p in tool_params if p.get("required", False)]
            }

            tool_list.append(f'''
        Tool(
            name="{tool_name}",
            description="{tool_desc}",
            inputSchema={json.dumps(input_schema, indent=16)}
        )''')

            tool_handlers.append(f'''
    if name == "{tool_name}":
        # TODO: Implement {tool_name}
        return [TextContent(type="text", text="Tool {tool_name} executed")]
''')

        # Generate resources section
        resource_list = []
        resource_handlers = []

        for resource in resources:
            res_uri = resource.get("uri", "resource://example")
            res_name = resource.get("name", "Example Resource")
            res_desc = resource.get("description", "Example resource")

            resource_list.append(f'''
        EmbeddedResource(
            uri="{res_uri}",
            name="{res_name}",
            description="{res_desc}",
            mimeType="text/plain"
        )''')

            resource_handlers.append(f'''
    if uri.startswith("{res_uri}"):
        return [TextContent(type="text", text="Resource {res_name} data")]
''')

        # Generate prompts section
        prompt_list = []
        prompt_handlers = []

        for prompt in prompts:
            prompt_name = prompt.get("name", "example_prompt")
            prompt_desc = prompt.get("description", "Example prompt")

            prompt_list.append(f'''
        {{
            "name": "{prompt_name}",
            "description": "{prompt_desc}"
        }}''')

            prompt_handlers.append(f'''
    if name == "{prompt_name}":
        return {{
            "messages": [
                {{
                    "role": "user",
                    "content": {{
                        "type": "text",
                        "text": "Example prompt for {prompt_name}"
                    }}
                }}
            ]
        }}
''')

        code = f'''#!/usr/bin/env python3
"""
{name} - {description}
Auto-generated by MCP Generator
"""

import asyncio
from typing import Any
from mcp.server import Server
from mcp.server.stdio import stdio_server
from mcp.types import Tool, TextContent, EmbeddedResource

# Initialize the MCP server
app = Server("{name}")

@app.list_tools()
async def list_tools() -> list[Tool]:
    """List available tools"""
    return [{"".join(tool_list) if tool_list else newline + "        # No tools defined"}
    ]

@app.call_tool()
async def call_tool(name: str, arguments: Any) -> list[TextContent]:
    """Handle tool execution"""
    {"".join(tool_handlers) if tool_handlers else "pass"}

    raise ValueError(f"Unknown tool: {{name}}")

@app.list_resources()
async def list_resources() -> list[EmbeddedResource]:
    """List available resources"""
    return [{"".join(resource_list) if resource_list else newline + "        # No resources defined"}
    ]

@app.read_resource()
async def read_resource(uri: str) -> list[TextContent]:
    """Read a specific resource"""
    {"".join(resource_handlers) if resource_handlers else "pass"}

    raise ValueError(f"Unknown resource: {{uri}}")

@app.list_prompts()
async def list_prompts() -> list[dict]:
    """List available prompts"""
    return [{"".join(prompt_list) if prompt_list else newline + "        # No prompts defined"}
    ]

@app.get_prompt()
async def get_prompt(name: str, arguments: dict) -> dict:
    """Get a specific prompt"""
    {"".join(prompt_handlers) if prompt_handlers else "pass"}

    raise ValueError(f"Unknown prompt: {{name}}")

async def main():
    """Run the MCP server"""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )

if __name__ == "__main__":
    asyncio.run(main())
'''
        return {
            "server.py": code,
            "README.md": f"# {name}\n\n{description}\n\n## Installation\n\n```bash\npip install -r requirements.txt\n```\n\n## Usage\n\n```bash\npython server.py\n```",
            "requirements.txt": "mcp>=0.9.0\n"
        }


@app.list_tools()
async def list_tools() -> list[Tool]:
    """List available MCP generator tools"""
    return [
        Tool(
            name="generate_mcp_server",
            description="Generate a new MCP server from a template. Creates a complete MCP server with the specified type and configuration.",
            inputSchema={
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "description": "Name of the MCP server (e.g., 'weather-server')"
                    },
                    "description": {
                        "type": "string",
                        "description": "Description of what the server does"
                    },
                    "server_type": {
                        "type": "string",
                        "enum": ["tool", "resource", "full"],
                        "description": "Type of MCP server: 'tool' (tools only), 'resource' (data resources), or 'full' (tools, resources, and prompts)"
                    },
                    "output_dir": {
                        "type": "string",
                        "description": "Output directory path where the server will be created"
                    },
                    "config": {
                        "type": "object",
                        "description": "Configuration object containing tools, resources, and prompts definitions",
                        "properties": {
                            "tools": {
                                "type": "array",
                                "description": "List of tools to generate",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {"type": "string"},
                                        "description": {"type": "string"},
                                        "parameters": {
                                            "type": "array",
                                            "items": {
                                                "type": "object",
                                                "properties": {
                                                    "name": {"type": "string"},
                                                    "type": {"type": "string"},
                                                    "description": {"type": "string"},
                                                    "required": {"type": "boolean"}
                                                }
                                            }
                                        }
                                    }
                                }
                            },
                            "resources": {
                                "type": "array",
                                "description": "List of resources to generate",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "uri": {"type": "string"},
                                        "name": {"type": "string"},
                                        "description": {"type": "string"},
                                        "type": {"type": "string"}
                                    }
                                }
                            },
                            "prompts": {
                                "type": "array",
                                "description": "List of prompts to generate",
                                "items": {
                                    "type": "object",
                                    "properties": {
                                        "name": {"type": "string"},
                                        "description": {"type": "string"}
                                    }
                                }
                            }
                        }
                    }
                },
                "required": ["name", "description", "server_type", "output_dir"]
            }
        ),
        Tool(
            name="list_templates",
            description="List all available MCP server templates with their descriptions and features",
            inputSchema={
                "type": "object",
                "properties": {}
            }
        ),
        Tool(
            name="validate_mcp_config",
            description="Validate a MCP server configuration before generation to ensure it's properly formatted",
            inputSchema={
                "type": "object",
                "properties": {
                    "config": {
                        "type": "object",
                        "description": "The configuration object to validate"
                    }
                },
                "required": ["config"]
            }
        ),
        Tool(
            name="generate_example_config",
            description="Generate an example configuration for a specific server type to help users get started",
            inputSchema={
                "type": "object",
                "properties": {
                    "server_type": {
                        "type": "string",
                        "enum": ["tool", "resource", "full"],
                        "description": "Type of server to generate example config for"
                    }
                },
                "required": ["server_type"]
            }
        )
    ]


@app.call_tool()
async def call_tool(name: str, arguments: Any) -> list[TextContent]:
    """Handle tool execution requests"""

    if name == "generate_mcp_server":
        server_name = arguments.get("name")
        description = arguments.get("description")
        server_type = arguments.get("server_type")
        output_dir = arguments.get("output_dir")
        config = arguments.get("config", {})

        try:
            # Create output directory
            output_path = Path(output_dir) / server_name
            output_path.mkdir(parents=True, exist_ok=True)

            # Generate files based on server type
            if server_type == "tool":
                tools = config.get("tools", [])
                files = MCPTemplate.basic_tool_server(server_name, description, tools)
            elif server_type == "resource":
                resources = config.get("resources", [])
                files = MCPTemplate.resource_server(server_name, description, resources)
            elif server_type == "full":
                files = MCPTemplate.full_server(server_name, description, config)
            else:
                return [TextContent(
                    type="text",
                    text=f"Error: Unknown server type '{server_type}'. Use 'tool', 'resource', or 'full'."
                )]

            # Write files
            for filename, content in files.items():
                file_path = output_path / filename
                file_path.write_text(content)

            newline = "\n"
            files_list = newline.join([f"  - {f}" for f in files.keys()])
            result = f"""✅ Successfully generated MCP server '{server_name}'!

📁 Location: {output_path}
📄 Files created:
{files_list}

🚀 Next steps:
1. cd {output_path}
2. pip install -r requirements.txt
3. python server.py

📖 Configuration for Cursor/Claude Code:
Add this to your MCP configuration:
{{
  "mcpServers": {{
    "{server_name}": {{
      "command": "python",
      "args": ["{output_path / 'server.py'}"]
    }}
  }}
}}
"""
            return [TextContent(type="text", text=result)]

        except Exception as e:
            return [TextContent(type="text", text=f"Error generating server: {str(e)}")]

    elif name == "list_templates":
        templates = """📋 Available MCP Server Templates:

1️⃣ Tool Server (type: "tool")
   - Purpose: Create MCP servers that provide tools/functions
   - Use case: API integrations, calculations, external service calls
   - Features: Custom tools with parameters and validation

2️⃣ Resource Server (type: "resource")
   - Purpose: Create MCP servers that expose data resources
   - Use case: Database access, file systems, data feeds
   - Features: URI-based resources with different MIME types

3️⃣ Full Server (type: "full")
   - Purpose: Complete MCP server with all features
   - Use case: Complex integrations requiring tools, resources, and prompts
   - Features: Tools, resources, prompts, and custom handlers

💡 Use 'generate_example_config' to see example configurations for each type.
"""
        return [TextContent(type="text", text=templates)]

    elif name == "validate_mcp_config":
        config = arguments.get("config", {})

        errors = []
        warnings = []

        # Validate tools
        if "tools" in config:
            for i, tool in enumerate(config["tools"]):
                if "name" not in tool:
                    errors.append(f"Tool {i}: Missing 'name' field")
                if "description" not in tool:
                    warnings.append(f"Tool {i}: Missing 'description' field")

                if "parameters" in tool:
                    for j, param in enumerate(tool["parameters"]):
                        if "name" not in param:
                            errors.append(f"Tool {i}, Parameter {j}: Missing 'name' field")

        # Validate resources
        if "resources" in config:
            for i, resource in enumerate(config["resources"]):
                if "uri" not in resource:
                    errors.append(f"Resource {i}: Missing 'uri' field")
                if "name" not in resource:
                    errors.append(f"Resource {i}: Missing 'name' field")

        # Validate prompts
        if "prompts" in config:
            for i, prompt in enumerate(config["prompts"]):
                if "name" not in prompt:
                    errors.append(f"Prompt {i}: Missing 'name' field")
                if "description" not in prompt:
                    warnings.append(f"Prompt {i}: Missing 'description' field")

        if errors:
            result = f"❌ Validation failed:\n\nErrors:\n" + "\n".join([f"  - {e}" for e in errors])
            if warnings:
                result += f"\n\nWarnings:\n" + "\n".join([f"  - {w}" for w in warnings])
        elif warnings:
            result = f"⚠️  Validation passed with warnings:\n\n" + "\n".join([f"  - {w}" for w in warnings])
        else:
            result = "✅ Configuration is valid!"

        return [TextContent(type="text", text=result)]

    elif name == "generate_example_config":
        server_type = arguments.get("server_type")

        examples = {
            "tool": {
                "tools": [
                    {
                        "name": "calculate",
                        "description": "Perform mathematical calculations",
                        "parameters": [
                            {
                                "name": "expression",
                                "type": "string",
                                "description": "Mathematical expression to evaluate",
                                "required": True
                            }
                        ]
                    },
                    {
                        "name": "convert_units",
                        "description": "Convert between different units",
                        "parameters": [
                            {
                                "name": "value",
                                "type": "number",
                                "description": "Value to convert",
                                "required": True
                            },
                            {
                                "name": "from_unit",
                                "type": "string",
                                "description": "Source unit",
                                "required": True
                            },
                            {
                                "name": "to_unit",
                                "type": "string",
                                "description": "Target unit",
                                "required": True
                            }
                        ]
                    }
                ]
            },
            "resource": {
                "resources": [
                    {
                        "uri": "data://weather",
                        "name": "Weather Data",
                        "description": "Current weather information",
                        "type": "json"
                    },
                    {
                        "uri": "data://config",
                        "name": "Configuration",
                        "description": "Server configuration data",
                        "type": "text"
                    }
                ]
            },
            "full": {
                "tools": [
                    {
                        "name": "search",
                        "description": "Search for information",
                        "parameters": [
                            {
                                "name": "query",
                                "type": "string",
                                "description": "Search query",
                                "required": True
                            }
                        ]
                    }
                ],
                "resources": [
                    {
                        "uri": "data://results",
                        "name": "Search Results",
                        "description": "Latest search results",
                        "type": "json"
                    }
                ],
                "prompts": [
                    {
                        "name": "analyze",
                        "description": "Analyze search results"
                    }
                ]
            }
        }

        if server_type in examples:
            example_json = json.dumps(examples[server_type], indent=2)
            result = f"""📝 Example configuration for '{server_type}' server:

```json
{example_json}
```

💡 Usage:
Use this configuration with the 'generate_mcp_server' tool:

```json
{{
  "name": "my-{server_type}-server",
  "description": "My custom {server_type} server",
  "server_type": "{server_type}",
  "output_dir": "./output",
  "config": {example_json}
}}
```
"""
        else:
            result = f"❌ Unknown server type: {server_type}"

        return [TextContent(type="text", text=result)]

    raise ValueError(f"Unknown tool: {name}")


async def main():
    """Run the MCP Generator server"""
    async with stdio_server() as (read_stream, write_stream):
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options()
        )


if __name__ == "__main__":
    asyncio.run(main())
